### ISSUE TITLE
README.md references nonexistent command

### ISSUE THREAD

**Issue by dowgird** [google/ko#254] opened 2020-12-01 10:57 UTC
ko auth login my.registry.io -u username --password-stdin`

from [README.md](https://github.com/google/ko/blame/master/README.md#L30) produces

    Error: unknown command "auth" for "ko"

This should probably be `crane auth`

**Comment by jonjohnsonjr** [comment] 2020-12-01 15:51
Yup! Dupe of https://github.com/google/ko/issues/155

Going to close this in favor of that issue, but it's currently in `master` and not in any release, so we need to cut a release (and fix the help text).

Thanks 😄

**Closed by jonjohnsonjr** 2020-12-01 15:51 UTC

**Comment by jonjohnsonjr** [comment] 2020-12-22 17:51
FWIW we cut v0.7.0 which should include this command (which I've moved to `ko login`).
