### ISSUE TITLE
"ko and go have mismatched GOROOT"  error when trying ko commands.

### ISSUE THREAD

**Issue by mayuchau** [google/ko#432] opened 2021-09-08 04:20 UTC
Hello,
I am referring this document to build knative-serving to get images from source code.
https://github.com/knative/serving/blob/main/DEVELOPMENT.md

I have configured go, ko tools properly.

```
$ go version
go version go1.17 linux/amd64

$ ko version
0.8.3
```
In the Deploy knative-serving stage when I am trying below ko command 

`ko apply --selector knative.dev/crd-install=true -Rf config/core/`

after waiting for more than 10 mins I am seeing below error message.

`$ ko apply --selector knative.dev/crd-install=true -Rf config/core/`

```
2021/09/06 05:13:23 NOTICE!
ko and go have mismatched GOROOT:
go/build.Default.GOROOT = "go"
$(go env GOROOT) = "/usr/local/go"

Inferring GOROOT="/usr/local/go"

Run this to remove this warning:
export GOROOT=$(go env GOROOT)

For more information see:
google/ko#106
2021/09/06 05:13:23 No matching credentials were found, falling back on anonymous
customresourcedefinition.apiextensions.k8s.io/images.caching.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/certificates.networking.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/configurations.serving.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/clusterdomainclaims.networking.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/domainmappings.serving.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/ingresses.networking.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/metrics.autoscaling.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/podautoscalers.autoscaling.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/revisions.serving.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/routes.serving.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/serverlessservices.networking.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/services.serving.knative.dev unchanged
[mayuchau@phoenix61861 serving]$ export GOROOT=$(go env GOROOT)
[mayuchau@phoenix61861 serving]$ ko apply --selector knative.dev/crd-install=true -Rf config/core/
`
```

as per the recommendation I am exporting GOROOT but again I am seeing same issue.

`export GOROOT=$(go env GOROOT)
`

I have asked this question to knative-serving team as well.
reference:  https://github.com/knative/serving/pull/11900#issuecomment-913449304

**Comment by rakyll** [comment] 2021-09-11 19:30
I think this is related to/a duplicate of https://github.com/google/ko/issues/305.

**Closed** 2021-09-16 17:48 UTC
